### ISSUE TITLE
Auth-Command structure

### ISSUE THREAD

**Issue by mbtamuli** [EasyEngine/auth-command#2]
## Site specific

- [ ] Set authentication

Only username and password

```
# Set HTTP auth with username=easyengine (default) and random password for example.com
ee auth create example.com

# Set HTTP auth with username=test and random password for example.com
ee auth create example.com --user=test

# Set HTTP auth with username=test and password=pass for example.com
ee auth create example.com --user=test --pass=test
```

- [ ] Change username and/or password for example.com

Following will overwrite whichever key is passed

```
 ee auth update example.com --user=test --pass=mylongpassword
```

- [ ]  Specify whitelisted IP v4 list

Set

```
ee auth update example.com --ip=1.1.1.1,2.2.2.2,3.0.0.0/8
```

Reset

```
ee auth update example.com --ip=off
```

- [ ] List user/pass and whitelisted IPs (if any)

```
ee auth info example.com
```

- [ ] Remove authentication for example.com

```
ee auth delete example.com
```

**Comment by mrrobot47** [comment]
Closing in favor of new structure as proposed in https://github.com/EasyEngine/auth-command/issues/3
